export const APPLICANT_REPOSITORY = 'APPLICANT_REPOSITORY';
export const APPLICATION_REPOSITORY = 'APPLICATION_REPOSITORY';
export const BROKER_REPOSITORY = 'BROKER_REPOSITORY';
export const TASK_REPOSITORY = 'TASK_REPOSITORY';
export const UPLOAD_REPOSITORY = 'UPLOAD_REPOSITORY';
