import { QueryInterface } from 'sequelize';

export async function up(queryInterface: QueryInterface): Promise<void> {
  const insertData = [
    {
      id: 1,
      application_id: 1,
      assigned_to: 'broker',
      assigned_to_broker_id: 1,
      due_date: new Date(new Date().getTime() + 7 * 24 * 60 * 60 * 1000),
      title: 'Upload license or passport photo',
      status: 'pending',
    },
    {
      id: 2,
      application_id: 1,
      assigned_to: 'broker',
      assigned_to_broker_id: 1,
      due_date: new Date(new Date().getTime() + 7 * 24 * 60 * 60 * 1000),
      title: 'Upload outgoing property title',
      status: 'completed',
    },
    {
      id: 3,
      application_id: 1,
      assigned_to: 'broker',
      assigned_to_broker_id: 1,
      due_date: new Date(new Date().getTime() + 7 * 24 * 60 * 60 * 1000),
      title: 'Upload last 2 pay slips',
      status: 'pending',
    },
    {
      id: 4,
      application_id: 2,
      assigned_to: 'broker',
      assigned_to_broker_id: 1,
      due_date: new Date(new Date().getTime() + -21 * 24 * 60 * 60 * 1000),
      completed_date: new Date(new Date().getTime() + -15 * 24 * 60 * 60 * 1000),
      title: 'Upload license or passport photo',
      status: 'pending',
    },
    {
      id: 5,
      application_id: 2,
      assigned_to: 'broker',
      assigned_to_broker_id: 1,
      due_date: new Date(new Date().getTime() + -21 * 24 * 60 * 60 * 1000),
      completed_date: new Date(new Date().getTime() + -14 * 24 * 60 * 60 * 1000),
      title: 'Upload outgoing property title',
      status: 'pending',
    },
    {
      id: 6,
      application_id: 2,
      assigned_to: 'broker',
      assigned_to_broker_id: 1,
      due_date: new Date(new Date().getTime() + -21 * 24 * 60 * 60 * 1000),
      completed_date: new Date(new Date().getTime() + -19 * 24 * 60 * 60 * 1000),
      title: 'Upload last 2 pay slips',
      status: 'pending',
    },
    {
      id: 7,
      application_id: 3,
      assigned_to: 'broker',
      assigned_to_broker_id: 2,
      due_date: new Date(new Date().getTime() + -21 * 24 * 60 * 60 * 1000),
      completed_date: new Date(new Date().getTime() + -15 * 24 * 60 * 60 * 1000),
      title: 'Upload license or passport photo',
      status: 'pending',
    },
    {
      id: 8,
      application_id: 3,
      assigned_to: 'broker',
      assigned_to_broker_id: 2,
      due_date: new Date(new Date().getTime() + -21 * 24 * 60 * 60 * 1000),
      completed_date: new Date(new Date().getTime() + -14 * 24 * 60 * 60 * 1000),
      title: 'Upload outgoing property title',
      status: 'completed',
    },
    {
      id: 9,
      application_id: 3,
      assigned_to: 'broker',
      assigned_to_broker_id: 2,
      due_date: new Date(new Date().getTime() + -21 * 24 * 60 * 60 * 1000),
      completed_date: new Date(new Date().getTime() + -19 * 24 * 60 * 60 * 1000),
      title: 'Upload last 2 pay slips',
      status: 'completed',
    },
  ];
  await queryInterface.bulkInsert('tasks', insertData);
  await queryInterface.sequelize.query('ALTER SEQUENCE tasks_id_seq RESTART WITH 10;');
}
